### ISSUE TITLE
Tabs not in dark mode for iPad

### ISSUE THREAD

**Issue by JMacalinao** [nathanwhit/DarkChrome#14]
This might be due to not having an available jailbroken iPad to test. 😁 If you need any help tracking this down, just let me know what to do.

![97147FDC-E9DB-4299-A198-A2A4B5AF87B7](https://user-images.githubusercontent.com/12725027/58384371-161dc480-801c-11e9-83f8-51f14dfa1b56.png)

**Comment by nathanwhit** [comment]
I put up a version on my beta repo that I'm hoping fixes this, try it out and let me know how it goes. The repo is : [nathanwhit.github.io/repo](nathanwhit.github.io/repo).

**Comment by JMacalinao** [comment]
Works perfectly now. Thanks!
