### ISSUE TITLE
DarkChrome crashes in Chrome M74

### ISSUE THREAD

**Issue by strangewiz** [nathanwhit/DarkChrome#6]
See https://bugs.chromium.org/p/chromium/issues/detail?id=950664 for context.

**Comment by nathanwhit** [comment]
I don't have permission to view that issue report, could you fill me in? (A screenshot/ghostbin works).
Additionally, what iOS version are you on? I'm aware of crashing on iOS 10.3, it potentially affects anything below iOS 11 though.

**Comment by strangewiz** [comment]
tabId has been removed, so DarkChrome is crashing with an exception:
 -[Tab tabId]: unrecognized selector sent to instance 0x280be1f00

cause, amongst other things:
https://chromium-review.googlesource.com/c/chromium/src/+/1475912

I can CC your email to the bug for access, if you like.

**Comment by nathanwhit** [comment]
Thanks, I took a look through the changes, and I just pushed a commit that _should_ fix this. 
I also pushed a new .deb file to the M74 branch under packages, if you could test it and let me know if the crashing is fixed that would be great, I appreciate the help.

**Comment by strangewiz** [comment]
Sorry, I'm just passing along the message from Chromium -- I don't have a jailbroken phone to test.

If you would like to build and run yourself, the instructions here might help: https://chromium.googlesource.com/chromium/src/+/HEAD/docs/ios/build_instructions.md

**Comment by nathanwhit** [comment]
My bad, missed that you weren't the original reporting user.
Regardless, thanks for your help/passing it along.

**Comment by strangewiz** [comment]
FYI 74.0.3729.121 is now in the App store if you'd like to test.
